@startuml
'https://plantuml.com/use-case-diagram

/'
 Sistema de Reserva d'Hotels:
Volem fer el disseny de casos d'ús d'una aplicació de reserva d'habitacions d'hotel, on els clients poden cercar hotels, fer reserves i cancel·lar-les si és el cas. D'altra banda, els administradors d'hotel poden gestionar les reserves i afegir nous hotels.
Important: quan una reserva s'apropa, cal enviar un recordatori de la reserva s'activa.
'/

left to right direction
skinparam packageStyle rect
actor Client
actor Admin
actor Sistema

rectangle "Sistema de Reserva d'Hotels" {
  Client --> (Cercar hotels)
  Client --> (Fer reserva)
  Client --> (Cancelar reserva)
  Sistema --> (Enviar recordatori)
  Admin --> (Gestionar reserves)
  Admin --> (Afegir hotel)
}

@enduml